-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."Вложения" DROP CONSTRAINT IF EXISTS "fk_вложение_сообщения";

ALTER TABLE IF EXISTS public."Входы" DROP CONSTRAINT IF EXISTS "fk_вход_пользователь";

ALTER TABLE IF EXISTS public."Пользователи" DROP CONSTRAINT IF EXISTS "fk_аккаунт";

ALTER TABLE IF EXISTS public."Реакции" DROP CONSTRAINT IF EXISTS "fk_реакция_пользователь";

ALTER TABLE IF EXISTS public."Реакции" DROP CONSTRAINT IF EXISTS "fk_реакция_сообщение";

ALTER TABLE IF EXISTS public."Сообщения" DROP CONSTRAINT IF EXISTS "fk_отправитель";

ALTER TABLE IF EXISTS public."Сообщения" DROP CONSTRAINT IF EXISTS "fk_получатель";

ALTER TABLE IF EXISTS public."Сообщения" DROP CONSTRAINT IF EXISTS "fk_чат_сообщения";

ALTER TABLE IF EXISTS public."Статусы_пользователей" DROP CONSTRAINT IF EXISTS "fk_статус_пользователь";

ALTER TABLE IF EXISTS public."Статусы_сообщений" DROP CONSTRAINT IF EXISTS "fk_статус_пользователь2";

ALTER TABLE IF EXISTS public."Статусы_сообщений" DROP CONSTRAINT IF EXISTS "fk_статус_сообщения";

ALTER TABLE IF EXISTS public."Уведомления" DROP CONSTRAINT IF EXISTS "fk_уведомление_пользователь";

ALTER TABLE IF EXISTS public."Участники_чата" DROP CONSTRAINT IF EXISTS "fk_участник_пользователь";

ALTER TABLE IF EXISTS public."Участники_чата" DROP CONSTRAINT IF EXISTS "fk_участник_чата";

ALTER TABLE IF EXISTS public."Чаты" DROP CONSTRAINT IF EXISTS "fk_создатель_чата";

ALTER TABLE IF EXISTS public."Черный_список" DROP CONSTRAINT IF EXISTS "fk_блок_кому";

ALTER TABLE IF EXISTS public."Черный_список" DROP CONSTRAINT IF EXISTS "fk_блок_от";



DROP TABLE IF EXISTS public."Вложения";

CREATE TABLE IF NOT EXISTS public."Вложения"
(
    "ID_вложения" uuid NOT NULL,
    "ID_сообщения" uuid NOT NULL,
    "Имя_файла" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Тип_файла" character varying(100) COLLATE pg_catalog."default",
    "Размер_в_байтах" integer,
    "URL" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Вложения_pkey" PRIMARY KEY ("ID_вложения")
);

DROP TABLE IF EXISTS public."Входы";

CREATE TABLE IF NOT EXISTS public."Входы"
(
    "ID_входа" uuid NOT NULL,
    "ID_пользователя" uuid NOT NULL,
    "Токен" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "IP_адрес" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "Время_захода" timestamp without time zone NOT NULL,
    "Время_выхода" timestamp without time zone,
    "Активен" boolean NOT NULL,
    CONSTRAINT "Входы_pkey" PRIMARY KEY ("ID_входа")
);

DROP TABLE IF EXISTS public."Настройки_аккаунта";

CREATE TABLE IF NOT EXISTS public."Настройки_аккаунта"
(
    "ID_настройки" uuid NOT NULL,
    "ID_аккаунта" uuid NOT NULL,
    "Аватар" text COLLATE pg_catalog."default",
    "Тема" character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT "Настройки_аккаунта_pkey" PRIMARY KEY ("ID_настройки"),
    CONSTRAINT "Настройки_аккаунта_ID_аккаунта_key" UNIQUE ("ID_аккаунта")
);

DROP TABLE IF EXISTS public."Пользователи";

CREATE TABLE IF NOT EXISTS public."Пользователи"
(
    "ID_пользователя" uuid NOT NULL,
    "ID_аккаунта" uuid NOT NULL,
    "Фамилия" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Имя" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Отчество" character varying(50) COLLATE pg_catalog."default",
    "Дата_рождения" date NOT NULL,
    "Дата_регистрации" date NOT NULL,
    "Логин" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Пароль" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Телефон" character(18) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Пользователи_pkey" PRIMARY KEY ("ID_пользователя")
);

DROP TABLE IF EXISTS public."Реакции";

CREATE TABLE IF NOT EXISTS public."Реакции"
(
    "ID_реакции" uuid NOT NULL,
    "ID_сообщения" uuid NOT NULL,
    "ID_пользователя" uuid NOT NULL,
    "Тип_реакции" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Реакции_pkey" PRIMARY KEY ("ID_реакции")
);

DROP TABLE IF EXISTS public."Сообщения";

CREATE TABLE IF NOT EXISTS public."Сообщения"
(
    "ID_сообщения" uuid NOT NULL,
    "ID_отправителя" uuid NOT NULL,
    "ID_получателя" uuid NOT NULL,
    "ID_чата" uuid NOT NULL,
    "Текст_сообщения" text COLLATE pg_catalog."default" NOT NULL,
    "Наличие_приложений" boolean NOT NULL,
    "Время_отправки" timestamp without time zone NOT NULL,
    CONSTRAINT "Сообщения_pkey" PRIMARY KEY ("ID_сообщения")
);

DROP TABLE IF EXISTS public."Статусы_пользователей";

CREATE TABLE IF NOT EXISTS public."Статусы_пользователей"
(
    "ID_пользователя" uuid NOT NULL,
    "Онлайн" boolean NOT NULL,
    "Последняя_активность" timestamp without time zone,
    CONSTRAINT "Статусы_пользователей_pkey" PRIMARY KEY ("ID_пользователя")
);

DROP TABLE IF EXISTS public."Статусы_сообщений";

CREATE TABLE IF NOT EXISTS public."Статусы_сообщений"
(
    "ID_сообщения" uuid NOT NULL,
    "ID_пользователя" uuid NOT NULL,
    "Статус" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Дата_изменения" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "Статусы_сообщений_pkey" PRIMARY KEY ("ID_сообщения", "ID_пользователя")
);

DROP TABLE IF EXISTS public."Уведомления";

CREATE TABLE IF NOT EXISTS public."Уведомления"
(
    "ID_уведомления" uuid NOT NULL,
    "ID_пользователя" uuid NOT NULL,
    "Текст" text COLLATE pg_catalog."default" NOT NULL,
    "Дата_создания" timestamp without time zone NOT NULL DEFAULT now(),
    "Прочитано" boolean NOT NULL DEFAULT false,
    CONSTRAINT "Уведомления_pkey" PRIMARY KEY ("ID_уведомления")
);

DROP TABLE IF EXISTS public."Участники_чата";

CREATE TABLE IF NOT EXISTS public."Участники_чата"
(
    "ID_чата" uuid NOT NULL,
    "ID_пользователя" uuid NOT NULL,
    "Роль" character varying(20) COLLATE pg_catalog."default" DEFAULT 'участник'::character varying,
    "Дата_вступления" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "Участники_чата_pkey" PRIMARY KEY ("ID_чата", "ID_пользователя")
);

DROP TABLE IF EXISTS public."Чаты";

CREATE TABLE IF NOT EXISTS public."Чаты"
(
    "ID_чата" uuid NOT NULL,
    "Название" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Тип" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "ID_пользователя" uuid NOT NULL,
    "Дата_создания" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "Чаты_pkey" PRIMARY KEY ("ID_чата")
);

DROP TABLE IF EXISTS public."Черный_список";

CREATE TABLE IF NOT EXISTS public."Черный_список"
(
    "ID_пользователя" uuid NOT NULL,
    "ID_заблокированного" uuid NOT NULL,
    "Дата_блокировки" timestamp without time zone DEFAULT now(),
    CONSTRAINT "Черный_список_pkey" PRIMARY KEY ("ID_пользователя", "ID_заблокированного")
);

ALTER TABLE IF EXISTS public."Вложения"
    ADD CONSTRAINT "fk_вложение_сообщения" FOREIGN KEY ("ID_сообщения")
    REFERENCES public."Сообщения" ("ID_сообщения") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Входы"
    ADD CONSTRAINT "fk_вход_пользователь" FOREIGN KEY ("ID_пользователя")
    REFERENCES public."Пользователи" ("ID_пользователя") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Пользователи"
    ADD CONSTRAINT "fk_аккаунт" FOREIGN KEY ("ID_аккаунта")
    REFERENCES public."Настройки_аккаунта" ("ID_аккаунта") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Реакции"
    ADD CONSTRAINT "fk_реакция_пользователь" FOREIGN KEY ("ID_пользователя")
    REFERENCES public."Пользователи" ("ID_пользователя") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Реакции"
    ADD CONSTRAINT "fk_реакция_сообщение" FOREIGN KEY ("ID_сообщения")
    REFERENCES public."Сообщения" ("ID_сообщения") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Сообщения"
    ADD CONSTRAINT "fk_отправитель" FOREIGN KEY ("ID_отправителя")
    REFERENCES public."Пользователи" ("ID_пользователя") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Сообщения"
    ADD CONSTRAINT "fk_получатель" FOREIGN KEY ("ID_получателя")
    REFERENCES public."Пользователи" ("ID_пользователя") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Сообщения"
    ADD CONSTRAINT "fk_чат_сообщения" FOREIGN KEY ("ID_чата")
    REFERENCES public."Чаты" ("ID_чата") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Статусы_пользователей"
    ADD CONSTRAINT "fk_статус_пользователь" FOREIGN KEY ("ID_пользователя")
    REFERENCES public."Пользователи" ("ID_пользователя") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "Статусы_пользователей_pkey"
    ON public."Статусы_пользователей"("ID_пользователя");


ALTER TABLE IF EXISTS public."Статусы_сообщений"
    ADD CONSTRAINT "fk_статус_пользователь2" FOREIGN KEY ("ID_пользователя")
    REFERENCES public."Пользователи" ("ID_пользователя") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Статусы_сообщений"
    ADD CONSTRAINT "fk_статус_сообщения" FOREIGN KEY ("ID_сообщения")
    REFERENCES public."Сообщения" ("ID_сообщения") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Уведомления"
    ADD CONSTRAINT "fk_уведомление_пользователь" FOREIGN KEY ("ID_пользователя")
    REFERENCES public."Пользователи" ("ID_пользователя") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Участники_чата"
    ADD CONSTRAINT "fk_участник_пользователь" FOREIGN KEY ("ID_пользователя")
    REFERENCES public."Пользователи" ("ID_пользователя") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Участники_чата"
    ADD CONSTRAINT "fk_участник_чата" FOREIGN KEY ("ID_чата")
    REFERENCES public."Чаты" ("ID_чата") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Чаты"
    ADD CONSTRAINT "fk_создатель_чата" FOREIGN KEY ("ID_пользователя")
    REFERENCES public."Пользователи" ("ID_пользователя") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Черный_список"
    ADD CONSTRAINT "fk_блок_кому" FOREIGN KEY ("ID_заблокированного")
    REFERENCES public."Пользователи" ("ID_пользователя") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Черный_список"
    ADD CONSTRAINT "fk_блок_от" FOREIGN KEY ("ID_пользователя")
    REFERENCES public."Пользователи" ("ID_пользователя") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;